## Grishma Parajuli
### Math T480 HW4

### Problem 1
Write a code to do an LU factorization of a given matrix with partial pivoting (Algorithm 21.1)

In [16]:
import numpy as np
def LU_factorization(A):
    m = A.shape[0]
    U = A
    P = np.identity(m)
    L = np.identity(m)
    
    for k in range(m-1):
        
        #pivoting
        if np.abs(U[k,k])==0:
            for i in range(k+1,m):
                if np.abs(U[i,k])>np.abs(U[k,k]):
                    # Swaps ith and kth rows to each other
                    U[[k,i]]=U[[i,k]]             
                    L[[k,i]]=L[[i,k]]
                    break

        #LU
        for j in range(k+1,m):
            L[j,k] = (U[j,k] / U[k,k])     
            U[j,k:m] -= np.dot(U[k,k:m],L[j,k])
        
    return P, L, U

### Problem 2
Use your code to factor a random 10 × 10 matrix.

In [17]:
A = np.random.random((10,10))
P1, L1, U1 = LU_factorization(A)
#print(P1)
print(L1)
print(U1)

[[  1.           0.           0.           0.           0.
    0.           0.           0.           0.           0.        ]
 [  0.46547416   1.           0.           0.           0.
    0.           0.           0.           0.           0.        ]
 [  0.38501717   2.49070114   1.           0.           0.
    0.           0.           0.           0.           0.        ]
 [  0.63026391 -34.98455219  -4.62252853   1.           0.
    0.           0.           0.           0.           0.        ]
 [  1.37934841 -38.29790454  -7.40278884   1.01801886   1.
    0.           0.           0.           0.           0.        ]
 [  0.62593687   1.90547881  -0.27621254  -0.03882545  -0.67365221
    1.           0.           0.           0.           0.        ]
 [  0.43086964 -30.14187658  -4.01066264   0.92532859   1.03044193
   -0.38654273   1.           0.           0.           0.        ]
 [  1.29590896 -10.2095464   -2.70198135   0.19891832  -0.50514547
    0.71687984  -0.3026872  

In [18]:
#CHECK
import scipy
import scipy.linalg as la
(P2, L2, U2) = la.lu(A)
print(U2)

[[ 6.57056848e-01  1.27545398e-01  9.65837342e-01  5.07677096e-01
   9.45568062e-01  1.63064661e-01  2.36003865e-01  5.31528000e-01
   8.18759324e-01  6.34661519e-01]
 [ 0.00000000e+00 -1.92719862e-02 -5.85002236e-02  3.79789804e-01
   1.64807515e-01  7.47225349e-01  8.81609564e-01 -1.90307967e-01
   1.87882269e-01  3.09620924e-01]
 [ 0.00000000e+00  0.00000000e+00  4.27169698e-01 -3.92521081e-01
   1.46304841e-01 -1.60836915e+00 -2.19623295e+00  7.68351327e-01
   7.61163673e-03 -6.95989187e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.12504630e+01
   6.39720629e+00  1.94725409e+01  2.07075947e+01 -2.86689438e+00
   7.07336250e+00  7.38718125e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  -3.95213527e-01 -2.76692315e+00 -3.52877238e+00  1.03427430e+00
  -8.71971628e-02 -1.33177932e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00 -2.23778226e+00 -3.64449041e+00  1.32537939e+00
   1.38267231e-01 -1.10825785e+00

### Problem 3
Use your code to do problem 22.2 from your book.

22.2. Experiment with solving 60 x 60 systems of equations Ax = b by Gaussian elimination with partial pivoting, with A having the form (22.4). Do you observe that the results are useless because of the growth factor of order ${2}^{60}$? At your first attempt you may not observe this, because the integer entries of A may prevent any rounding errors from occurring. If so, find a way to modify your problem slightly so that the growth factor is the same or nearly so and catastrophic rounding errors really do take place.

In [19]:
#create A as a matrix of -1's in lower triangular area, 1's on diagonal and last column
m = 60
x = -1*np.ones((m,m))
B = np.tril(x)
B[:,-1] = 1
np.fill_diagonal(B, 1)
print (B)
P3, L3, U3 = LU_factorization(B)
print (U3)

[[ 1.  0.  0. ...  0.  0.  1.]
 [-1.  1.  0. ...  0.  0.  1.]
 [-1. -1.  1. ...  0.  0.  1.]
 ...
 [-1. -1. -1. ...  1.  0.  1.]
 [-1. -1. -1. ... -1.  1.  1.]
 [-1. -1. -1. ... -1. -1.  1.]]
[[1.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 1.00000000e+00]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 2.00000000e+00]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 4.00000000e+00]
 ...
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 1.00000000e+00
  0.00000000e+00 1.44115188e+17]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  1.00000000e+00 2.88230376e+17]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 5.76460752e+17]]


For this 60x60 matrix,the growth factor is $\rho={2}^{60} [i.e \approx {10}^{18}].$The results are useless because of the huge growth factor.